### ISSUE TITLE
Issues with unprintable characters

### ISSUE THREAD

**Issue by buzzsawddog** [tools4j/spockito#6]
I have several situations where I take a look at user input or things in the database.  If they have unwanted characters or strings I throw an exception.  I am in the process of writing tests that check for the strings and running into a problem with non printable characters.  for example I do  `"|\u0001|"` it ends up being empty string but doing `"|a\u0001a|"` allows the nonprintable character with a on either side.

I am going to include a pull request demonstrating the issue. `testUnprintableCharacters()` and `testUnprintableCharactersWrapped()`.  My thinking is that they would both pass as they are identical with the exception of the a warping the special character.

https://github.com/tools4j/spockito/pull/5 will show the the issue.

**Comment by terzerm** [comment]
The solution is the add single quotes around the characters.

Note that by default whitespace is removed, hence the solution is to surround non-printable or whitespace characters with single quotes. An example with String and char datatype has been added to [FaqTest.java](https://github.com/tools4j/spockito/blob/master/src/test/java/org/tools4j/spockito/FaqTest.java).

**Comment by buzzsawddog** [comment]
@terzerm  I appreciate it thanks!  Makes my life much easier ;-)
