### ISSUE TITLE
ArtifactId does not exist on Maven Central

### ISSUE THREAD

**Issue by sidcoelho** [tools4j/spockito#8]
I tried downloading `spockito-junit5:2.0` from Maven Central and it does not exist.
I could find only `tools4j-spockito:1.6` from 2017.

**Comment by terzerm** [comment]
hi

you are right we have been working on spockito 2.0 with support for junit 5 but this has not been released yet.

i hope we will be able to release it in the next 1-2 months.

**Comment by terzerm** [comment]
V2.0 has been released today.
