### ISSUE TITLE
Where is the version 2.0?

### ISSUE THREAD

**Issue by sidcoelho** [tools4j/spockito#9]
Hi. I´m really looking forward to using this lib but all I can found on Maven Central is `tools4j-spockito:1.6`.

Where is `spockito-junit5:2.0`? The former version doesn´t have the `@TableSource` annotation and I could not find a way to use it since the documentation for jUnit4 is showing 404.

**Comment by sidcoelho** [comment]
Sorry I forgot I had already opened that issue and didn´t see you had already responded.
My bad.

**Comment by terzerm** [comment]
V2.0 has been released today.
